SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
-- GRANT ALL ON SCHEMA public TO PUBLIC;	-- ??? A vérifier car issu des anciens scripts
GRANT USAGE ON SCHEMA public TO endiv_reader;
GRANT USAGE ON SCHEMA public TO endiv_owner;
GRANT USAGE ON SCHEMA pgis TO endiv_reader;
GRANT USAGE ON SCHEMA pgis TO endiv_owner;

-- FUNCTIONS
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM postgres;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO postgres;
-- GRANT ALL ON ALL FUNCTIONS TO PUBLIC;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO endiv_owner;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA pgis TO endiv_owner;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA pgis TO endiv_reader;

-- TABLES
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM postgres;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM endiv_reader;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres;
-- GRANT ALL ON ALL FUNCTIONS TO PUBLIC;
GRANT ALL ON ALL TABLES IN SCHEMA public TO endiv_owner;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO endiv_reader;
GRANT ALL ON ALL TABLES IN SCHEMA pgis TO endiv_owner;
GRANT SELECT ON ALL TABLES IN SCHEMA pgis TO endiv_reader;

-- SEQUENCES
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM postgres;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM endiv_reader;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres;
-- GRANT ALL ON ALL FUNCTIONS TO PUBLIC;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO endiv_owner;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO endiv_reader;

-- ALTER DEFAULT PRIVILEGES allows you to set the privileges that will be applied to objects created in the future.
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES  FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES  FROM postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES  TO postgres;
-- ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS  TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES  TO endiv_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES  FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES  FROM postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES  TO postgres;
-- ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS  TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES  TO endiv_owner;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES  TO endiv_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS  FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS  FROM postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS  TO postgres;
-- ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS  TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS  TO endiv_owner;
ALTER DEFAULT PRIVILEGES IN SCHEMA pgis GRANT ALL ON FUNCTIONS  TO endiv_owner;
ALTER DEFAULT PRIVILEGES IN SCHEMA pgis GRANT ALL ON FUNCTIONS  TO endiv_reader;

REVOKE INSERT ON calendar_element FROM endiv_owner;
REVOKE DELETE ON calendar_element FROM endiv_owner;
REVOKE UPDATE ON calendar_element FROM endiv_owner;
