INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (1,97,'Lundi à vendredi','true','true','true','true','true','false','false');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (2,97,'Samedi','false','false','false','false','false','true','false');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (3,97,'Lundi à vendredi en vacances scolaires','true','true','true','true','true','false','false');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (4,36,'Lundi à vendredi','true','true','true','true','true','false','false');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (5,36,'Samedi','false','false','false','false','false','true','false');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (6,36,'Lundi à vendredi en vacances scolaires','true','true','true','true','true','false','false');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (7,36,'Dimanche et jours fériés','false','false','false','false','false','false','true');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (8,86,'Lundi à vendredi','true','true','true','true','true','false','false');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (9,86,'Samedi','false','false','false','false','false','true','false');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (10,86,'Lundi à vendredi en vacances scolaires','true','true','true','true','true','false','false');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (11,86,'Dimanche et jours fériés','false','false','false','false','false','false','true');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (12,91,'Lundi à dimanche','true','true','true','true','true','true','true');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (13,34,'Lundi à vendredi','true','true','true','true','true','false','false');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (14,34,'Samedi','false','false','false','false','false','true','false');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (15,34,'Dimanche et jours fériés','false','false','false','false','false','false','true');
INSERT INTO grid_calendar(id, line_version_id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (16,34,'Lundi à vendredi en vacances scolaires','true','true','true','true','true','false','false');

INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (1,2,3,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (2,5,3,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (3,9,3,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (4,1,1,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (5,4,1,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (6,8,1,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (7,1,8,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (8,4,8,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (9,8,8,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (10,3,5,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (11,6,5,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (12,10,5,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (13,12,6,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (14,12,7,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (15,7,4,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (16,11,4,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (17,7,9,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (18,11,9,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (19,7,10,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (20,11,10,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (21,12,1,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (22,12,2,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (23,12,3,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (24,12,4,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (25,12,5,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (26,12,8,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (27,12,9,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (28,12,10,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (29,13,1,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (30,14,3,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (31,15,4,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (32,15,9,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (33,15,10,'true');
INSERT INTO grid_link_calendar_mask_type(id, grid_calendar_id, grid_mask_type_id, active) VALUES (34,16,5,'true');
