CREATE SCHEMA ogive;
ALTER SCHEMA ogive OWNER TO :owner;

GRANT ALL PRIVILEGES ON SCHEMA ogive TO :owner;
GRANT USAGE ON SCHEMA ogive TO :reader;
GRANT SELECT ON ALL TABLES IN SCHEMA ogive TO :reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA ogive GRANT SELECT ON TABLES TO :reader;
