SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

-- SCHEMA
REVOKE ALL ON SCHEMA ogive FROM PUBLIC;
REVOKE ALL ON SCHEMA ogive FROM postgres;
GRANT ALL ON SCHEMA ogive TO postgres;
GRANT USAGE ON SCHEMA ogive TO :reader;
GRANT USAGE ON SCHEMA ogive TO :owner;

-- FUNCTIONS
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA ogive FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA ogive FROM postgres;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA ogive TO postgres;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA ogive TO :owner;

-- TABLES
REVOKE ALL ON ALL TABLES IN SCHEMA ogive FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA ogive FROM postgres;
REVOKE ALL ON ALL TABLES IN SCHEMA ogive FROM :reader;
GRANT ALL ON ALL TABLES IN SCHEMA ogive TO postgres;
GRANT ALL ON ALL TABLES IN SCHEMA ogive TO :owner;
GRANT SELECT ON ALL TABLES IN SCHEMA ogive TO :reader;

-- SEQUENCES
REVOKE ALL ON ALL SEQUENCES IN SCHEMA ogive FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA ogive FROM postgres;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA ogive FROM :reader;
GRANT ALL ON ALL SEQUENCES IN SCHEMA ogive TO postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA ogive TO :owner;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA ogive TO :reader;

-- ALTER DEFAULT PRIVILEGES allows you to set the privileges that will be applied to objects created in the future.
ALTER DEFAULT PRIVILEGES IN SCHEMA ogive REVOKE ALL ON TABLES  FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA ogive REVOKE ALL ON TABLES  FROM postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA ogive GRANT ALL ON TABLES  TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA ogive GRANT ALL ON TABLES  TO :owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA ogive REVOKE ALL ON SEQUENCES  FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA ogive REVOKE ALL ON SEQUENCES  FROM postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA ogive GRANT ALL ON SEQUENCES  TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA ogive GRANT ALL ON SEQUENCES  TO :owner;
ALTER DEFAULT PRIVILEGES IN SCHEMA ogive GRANT SELECT ON SEQUENCES  TO :reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA ogive REVOKE ALL ON FUNCTIONS  FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA ogive REVOKE ALL ON FUNCTIONS  FROM postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA ogive GRANT ALL ON FUNCTIONS  TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA ogive GRANT ALL ON FUNCTIONS  TO :owner;
